import { NextRequest } from "next/server";
import { loadReport } from "@/lib/storage";
import { getCurrentUser } from "@/lib/auth";
import { limitsFor } from "@/lib/plans";
import { hostOf } from "@/lib/utils";
import { CATEGORY_LABELS, type CheckCategory } from "@/lib/audit/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Lightweight, dependency-light PDF: we render a clean printable HTML and let
// the report be saved as PDF. @react-pdf is heavy on the edge; for v1 we serve
// a self-contained printable HTML document with an auto-print hint, which is
// reliable across serverless runtimes and gives a clean PDF via the browser.
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;
  const report = await loadReport(slug);
  if (!report) return new Response("Not found", { status: 404 });

  const user = await getCurrentUser();
  if (!user || !limitsFor(user.plan).pdfExport) {
    return new Response("PDF export is a Pro feature.", { status: 403 });
  }

  const host = hostOf(report.url);
  const rows = report.categories
    .map((c) => {
      const findings = c.findings
        .map(
          (f) =>
            `<tr><td>${f.severity === "pass" ? "✓" : f.severity === "warn" ? "!" : "✗"}</td><td>${escapeHtml(
              f.title,
            )}</td><td style="text-align:right">${f.earned}/${f.max}</td></tr>`,
        )
        .join("");
      return `<h3>${CATEGORY_LABELS[c.category as CheckCategory]} — ${c.earned}/${c.max}</h3>
        <table>${findings}</table>`;
    })
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8">
  <title>Citegrade report — ${host}</title>
  <style>
    body{font-family:-apple-system,Segoe UI,sans-serif;color:#111;max-width:760px;margin:40px auto;padding:0 24px}
    h1{font-size:28px;margin:0 0 4px}
    .score{font-size:64px;font-weight:800;color:#5e5ce6}
    .muted{color:#666;font-size:13px}
    table{width:100%;border-collapse:collapse;margin:8px 0 20px}
    td{padding:6px 8px;border-bottom:1px solid #eee;font-size:13px}
    h3{margin-top:24px;font-size:15px}
    .head{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:2px solid #5e5ce6;padding-bottom:16px;margin-bottom:24px}
    @media print{.noprint{display:none}}
  </style></head><body onload="window.print()">
  <div class="head">
    <div><h1>${host}</h1><p class="muted">AI SEO audit · ${new Date(report.fetchedAt).toLocaleString()}</p></div>
    <div style="text-align:right"><div class="score">${report.score}</div><div class="muted">/100 · Grade ${report.grade}</div></div>
  </div>
  <p><strong>${escapeHtml(report.verdict)}</strong></p>
  ${rows}
  <p class="muted" style="margin-top:32px">Generated by Citegrade · the 100-point AI SEO audit</p>
  <button class="noprint" onclick="window.print()" style="margin-top:16px;padding:10px 16px;background:#5e5ce6;color:#fff;border:none;border-radius:8px;cursor:pointer">Save as PDF</button>
  </body></html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
